jetton_minter:
  data: fift/minter_data.fif
  func:
    - ../contracts/op-codes.fc
    - ../contracts/send-modes.fc
    - ../contracts/params.fc
    - func/utils/helpers.func
    - ../contracts/jetton-utils.fc
    - ../contracts/jetton-minter.fc
  tests:
    - tests/minter-tests.func
    - tests/minter-tests-int.func

jetton_wallet:
  data: fift/wallet_data.fif
  func: 
    - ../contracts/op-codes.fc
    - ../contracts/send-modes.fc
    - ../contracts/params.fc
    - func/utils/helpers.func
    - ../contracts/jetton-utils.fc
    - ../contracts/jetton-wallet.fc
  tests:
    - tests/wallet-tests.func
    - tests/wallet-tests-int.func

